//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Banks
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Account_Name { get; set; }
        public string Account_Number { get; set; }
        public string Swift_Code { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
