//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc_Treasury_Bank_Transactions
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<int> Transaction_By { get; set; }
        public Nullable<bool> Is_Bank { get; set; }
        public Nullable<int> Treasury_Bank_ID { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public Nullable<int> Item_Main_ID { get; set; }
        public Nullable<int> Item_Sub_ID { get; set; }
        public Nullable<bool> Is_Expense { get; set; }
        public Nullable<decimal> Income_Amount { get; set; }
        public Nullable<decimal> Expense_Amount { get; set; }
        public Nullable<int> Main_Item_ID { get; set; }
        public Nullable<int> Sub_Item_ID { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
