//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance_Coupons
    {
        public int ID { get; set; }
        public string Serial { get; set; }
        public string Scratch_Code { get; set; }
        public Nullable<int> Activated_To { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Sold_To { get; set; }
        public Nullable<System.DateTime> Sold_Date { get; set; }
        public Nullable<int> Sold_by { get; set; }
        public string Used_For { get; set; }
    }
}
