//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Religion { get; set; }
        public string Nationality { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PlaceOfBirth { get; set; }
        public string Addreess { get; set; }
        public Nullable<int> Gov_ID { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string MaritalStatus { get; set; }
        public string Email { get; set; }
        public string MilitaryStatus { get; set; }
        public string FatherJob { get; set; }
        public string MotherJob { get; set; }
        public string GeneralServiceStatus { get; set; }
        public string FirstUniversityDegree { get; set; }
        public string University { get; set; }
        public string Major { get; set; }
        public string FacultyGrade { get; set; }
        public string GraduationYear { get; set; }
        public string GraduationProject { get; set; }
        public string Lang1 { get; set; }
        public string Lang1Deg { get; set; }
        public string Lang2 { get; set; }
        public string Lang2Deg { get; set; }
        public string Lang3 { get; set; }
        public string Lang3Deg { get; set; }
        public string CurrJobTitle { get; set; }
        public string CurrEmployer { get; set; }
        public Nullable<System.DateTime> CurrStartDate { get; set; }
        public Nullable<System.DateTime> CurrEndDate { get; set; }
        public string CurrJobDesc { get; set; }
        public string CurrJobBasicSalary { get; set; }
        public string CurrJobSalaryBonus { get; set; }
        public string PrevJobTitle1 { get; set; }
        public string PrevEmployer1 { get; set; }
        public Nullable<System.DateTime> PrevStartDate1 { get; set; }
        public Nullable<System.DateTime> PrevEndDate1 { get; set; }
        public string PrevJobDesc1 { get; set; }
        public string PrevJobTitle2 { get; set; }
        public string PrevEmployer2 { get; set; }
        public Nullable<System.DateTime> PrevStartDate2 { get; set; }
        public Nullable<System.DateTime> PrevEndDate2 { get; set; }
        public string PrevJobDesc2 { get; set; }
        public string ExperienceYears { get; set; }
        public string ComputerSkills { get; set; }
        public string Certificate { get; set; }
        public string Availability { get; set; }
        public string JobCountry { get; set; }
        public Nullable<int> BankOfferdJob_ID { get; set; }
        public string JobField1 { get; set; }
        public string JobField2 { get; set; }
        public string SalaryAmount { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string CVPath { get; set; }
    }
}
