//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Service_Report
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Referrer_ID { get; set; }
        public string The_Challenge { get; set; }
        public string The_Response { get; set; }
        public Nullable<int> Means_Of_Communication_ID { get; set; }
        public Nullable<int> Challenges_ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> By_Admin_ID { get; set; }
    }
}
