//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Follow
    {
        public int ID { get; set; }
        public string Lead_Name { get; set; }
        public Nullable<int> Gov_ID { get; set; }
        public Nullable<int> Invitation_Type_ID { get; set; }
        public Nullable<System.DateTime> Invitation_Date { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Master_ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
    }
}
