//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diploma_Location
    {
        public int ID { get; set; }
        public string Place_Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Students_Count { get; set; }
        public string Account_Manger_Name { get; set; }
        public string Account_Manger_Phone { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
