//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dist_Rankss
    {
        public int ID { get; set; }
        public string Level_Status { get; set; }
        public string Right_Side { get; set; }
        public string Left_Side { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Reward { get; set; }
        public Nullable<int> Sponsor { get; set; }
    }
}
