//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributors_Addon_Coins_12_06_2020
    {
        public int ID { get; set; }
        public Nullable<int> Distributors_ID { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Description { get; set; }
    }
}
