//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_National_ID
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public string National_ID_Front { get; set; }
        public string National_ID_Back { get; set; }
        public Nullable<System.DateTime> Upload_Date { get; set; }
    }
}
