//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributors_Annual_renewal
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public Nullable<System.DateTime> Renewal_Date { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<System.DateTime> Renewal_Time { get; set; }
    }
}
