//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Pending_Activation
    {
        public int ID { get; set; }
        public Nullable<int> New_Dist_ID { get; set; }
        public Nullable<System.DateTime> Subscription_Date { get; set; }
        public Nullable<int> Subscribed_By { get; set; }
        public Nullable<int> Nearst_NS_ID { get; set; }
        public Nullable<bool> Is_Activated { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public Nullable<int> Activated_By_ID { get; set; }
    }
}
