//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dist_Ref
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<double> National_ID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public Nullable<double> Gov_ID { get; set; }
        public Nullable<double> City_ID { get; set; }
        public string Gender { get; set; }
        public string Registration_Method { get; set; }
        public string BirthDate { get; set; }
        public Nullable<double> Activation_2016 { get; set; }
        public Nullable<double> Guide_ID { get; set; }
    }
}
