//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Serial_Paswword
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public string Serial { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Reset_Token { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public Nullable<bool> IS_Changed { get; set; }
    }
}
