//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distributor_Password
    {
        public int Distributor_ID { get; set; }
        public string Password { get; set; }
        public string Reset_Token { get; set; }
        public Nullable<bool> Password_Updateable { get; set; }
    }
}
