//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dopay
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public string Dopay_ID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<bool> Dopay_Is_Active { get; set; }
        public Nullable<System.DateTime> Dopay_Activation_Date { get; set; }
        public Nullable<int> Dopay_Type { get; set; }
    }
}
