//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Easy_pay_cards
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public string Name_AR { get; set; }
        public string National_ID { get; set; }
        public string Card_ID { get; set; }
        public string National_ID_No { get; set; }
        public string Card_ID_No { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
