//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elite_Place_Branchs
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Elite_Place_ID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Gov_ID { get; set; }
    }
}
