//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events_Ticket_Holders
    {
        public int ID { get; set; }
        public Nullable<int> Event_ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public Nullable<int> Tickets_Count { get; set; }
        public Nullable<int> Total_Cost { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public Nullable<bool> Is_Paid { get; set; }
        public Nullable<bool> Is_Delivered { get; set; }
        public Nullable<int> Delivered_By { get; set; }
        public Nullable<System.DateTime> Delivery_Date { get; set; }
        public string OrderNumber { get; set; }
        public string Subscription_Type { get; set; }
    }
}
