//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fawry_Payment
    {
        public int ID { get; set; }
        public Nullable<int> Distributors_ID { get; set; }
        public Nullable<decimal> Order_Amount { get; set; }
        public Nullable<decimal> Order_Point { get; set; }
        public Nullable<decimal> Paid_Amount { get; set; }
        public Nullable<decimal> Paid_point { get; set; }
        public Nullable<System.DateTime> Creation_date { get; set; }
        public Nullable<System.DateTime> Update_date { get; set; }
        public string Status { get; set; }
        public string Fawry_Ref_No { get; set; }
        public string Fawry_No { get; set; }
    }
}
