//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image_Slider
    {
        public int ID { get; set; }
        public string Image_Text { get; set; }
        public string Image_Text_Ar { get; set; }
        public string Image_Path { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
