//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int ID { get; set; }
        public Nullable<int> Distributors_ID { get; set; }
        public string Inv_name { get; set; }
        public string mobile { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Referrer_ID { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<bool> done { get; set; }
    }
}
