//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Descr { get; set; }
        public string TitleStyle { get; set; }
        public string DescrStyle { get; set; }
        public string TitleAr { get; set; }
        public string DescrAr { get; set; }
        public string TitleStyleAr { get; set; }
        public string DescrStyleAr { get; set; }
    }
}
