//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level_Status_Ranks
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Profit_Rate { get; set; }
        public Nullable<decimal> Silver_Profit_Rate { get; set; }
        public Nullable<decimal> Bronze_Profit_Rate { get; set; }
        public Nullable<decimal> Leader_Ship_Points { get; set; }
        public Nullable<decimal> Bronze_LeaderShip_Points { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
