//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int MenuID { get; set; }
        public string MenuTitle { get; set; }
        public string MenuTitleAr { get; set; }
        public string MenuDesc { get; set; }
        public string MenuIcon { get; set; }
        public bool MenuDisplay { get; set; }
        public int MenuOrder { get; set; }
        public string MenuPage { get; set; }
        public int MenuParentID { get; set; }
        public System.DateTime MenuDateAdded { get; set; }
        public bool MenuIsAdmin { get; set; }
        public string Style { get; set; }
        public string StyleAr { get; set; }
    }
}
