//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Network_Video
    {
        public int ID { get; set; }
        public string Name_Videos { get; set; }
        public string Url { get; set; }
        public string Image { get; set; }
        public string Instructor { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
