//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Brief { get; set; }
        public Nullable<int> Reads { get; set; }
        public Nullable<System.DateTime> Publish_Date { get; set; }
        public Nullable<int> Writer_ID { get; set; }
        public string Photo_Path { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
