//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_Starting_Balance
    {
        public int ID { get; set; }
        public Nullable<int> NS_ID { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Daily_Starting_Balance { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
