//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NS_Upgrade
    {
        public int ID { get; set; }
        public Nullable<int> Dist_ID { get; set; }
        public Nullable<int> NS_ID { get; set; }
    }
}
