//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Plan_BEntities : DbContext
    {
        public Plan_BEntities()
            : base("name=Plan_BEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__Products> C__Products { get; set; }
        public virtual DbSet<Acc_Banks> Acc_Banks { get; set; }
        public virtual DbSet<Acc_Compny_Balance> Acc_Compny_Balance { get; set; }
        public virtual DbSet<Acc_Items> Acc_Items { get; set; }
        public virtual DbSet<Acc_Items_Main> Acc_Items_Main { get; set; }
        public virtual DbSet<Acc_Items_Sub> Acc_Items_Sub { get; set; }
        public virtual DbSet<Acc_Main_Expense> Acc_Main_Expense { get; set; }
        public virtual DbSet<Acc_Main_Income> Acc_Main_Income { get; set; }
        public virtual DbSet<Acc_Money_Type> Acc_Money_Type { get; set; }
        public virtual DbSet<Acc_Sub_Expense> Acc_Sub_Expense { get; set; }
        public virtual DbSet<Acc_Sub_Income> Acc_Sub_Income { get; set; }
        public virtual DbSet<Acc_Treasury> Acc_Treasury { get; set; }
        public virtual DbSet<Acc_Treasury_Bank_Transactions> Acc_Treasury_Bank_Transactions { get; set; }
        public virtual DbSet<Acc_User_Transaction_Type> Acc_User_Transaction_Type { get; set; }
        public virtual DbSet<Acc_Users> Acc_Users { get; set; }
        public virtual DbSet<Activated_Distributors> Activated_Distributors { get; set; }
        public virtual DbSet<Admin_History> Admin_History { get; set; }
        public virtual DbSet<Admin_Menus> Admin_Menus { get; set; }
        public virtual DbSet<Admin_User_Menus> Admin_User_Menus { get; set; }
        public virtual DbSet<Admin_User_Pages> Admin_User_Pages { get; set; }
        public virtual DbSet<Administrator_Type> Administrator_Type { get; set; }
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Available_Job> Available_Job { get; set; }
        public virtual DbSet<Balance_Coupons> Balance_Coupons { get; set; }
        public virtual DbSet<Best_Profit> Best_Profit { get; set; }
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<Cashing_Balance_Request> Cashing_Balance_Request { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Commission> Commissions { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer_Service> Customer_Service { get; set; }
        public virtual DbSet<Customer_Service_Report> Customer_Service_Report { get; set; }
        public virtual DbSet<Daily_Follow> Daily_Follow { get; set; }
        public virtual DbSet<Daily_Follow_Invetation_Type> Daily_Follow_Invetation_Type { get; set; }
        public virtual DbSet<Diploma_11> Diploma_11 { get; set; }
        public virtual DbSet<Diploma_Attendance_Type> Diploma_Attendance_Type { get; set; }
        public virtual DbSet<Diploma_Cards> Diploma_Cards { get; set; }
        public virtual DbSet<Diploma_Details> Diploma_Details { get; set; }
        public virtual DbSet<Diploma_Grades> Diploma_Grades { get; set; }
        public virtual DbSet<Diploma_Instructors> Diploma_Instructors { get; set; }
        public virtual DbSet<Diploma_Location> Diploma_Location { get; set; }
        public virtual DbSet<Diploma> Diplomas { get; set; }
        public virtual DbSet<Dist_Ranks> Dist_Ranks { get; set; }
        public virtual DbSet<Dist_Rankss> Dist_Rankss { get; set; }
        public virtual DbSet<Dist_Ref> Dist_Ref { get; set; }
        public virtual DbSet<Distributor_Authorization_Doc> Distributor_Authorization_Doc { get; set; }
        public virtual DbSet<Distributor_Browser_Cookie> Distributor_Browser_Cookie { get; set; }
        public virtual DbSet<Distributor_Diploma_Referrer_Gold> Distributor_Diploma_Referrer_Gold { get; set; }
        public virtual DbSet<Distributor_Login_courses> Distributor_Login_courses { get; set; }
        public virtual DbSet<Distributor_Login_History> Distributor_Login_History { get; set; }
        public virtual DbSet<Distributor_National_ID> Distributor_National_ID { get; set; }
        public virtual DbSet<Distributor_Password> Distributor_Password { get; set; }
        public virtual DbSet<Distributor_Pending_Activation> Distributor_Pending_Activation { get; set; }
        public virtual DbSet<Distributor_Products> Distributor_Products { get; set; }
        public virtual DbSet<Distributor_Relatives> Distributor_Relatives { get; set; }
        public virtual DbSet<Distributor_Serial_Paswword> Distributor_Serial_Paswword { get; set; }
        public virtual DbSet<Distributor_Token> Distributor_Token { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<Distributors_Account_Balance> Distributors_Account_Balance { get; set; }
        public virtual DbSet<Distributors_Account_Balance_Sing_Up> Distributors_Account_Balance_Sing_Up { get; set; }
        public virtual DbSet<Distributors_Addon_Coins> Distributors_Addon_Coins { get; set; }
        public virtual DbSet<Distributors_Annual_renewal> Distributors_Annual_renewal { get; set; }
        public virtual DbSet<Distributors_Coins_Cash> Distributors_Coins_Cash { get; set; }
        public virtual DbSet<Distributors_Deleted> Distributors_Deleted { get; set; }
        public virtual DbSet<Distributors_Diploma> Distributors_Diploma { get; set; }
        public virtual DbSet<Distributors_Diploma_Attendance_History> Distributors_Diploma_Attendance_History { get; set; }
        public virtual DbSet<Distributors_Diploma_Deleted> Distributors_Diploma_Deleted { get; set; }
        public virtual DbSet<Distributors_Dopay_renewal> Distributors_Dopay_renewal { get; set; }
        public virtual DbSet<Distributors_Invited_Course> Distributors_Invited_Course { get; set; }
        public virtual DbSet<Distributors_PrePaidCards> Distributors_PrePaidCards { get; set; }
        public virtual DbSet<Distributors_Request_Transfer> Distributors_Request_Transfer { get; set; }
        public virtual DbSet<Distributors_Requests> Distributors_Requests { get; set; }
        public virtual DbSet<Distributors_Summit_Coins> Distributors_Summit_Coins { get; set; }
        public virtual DbSet<Distributors_Temp> Distributors_Temp { get; set; }
        public virtual DbSet<Distributors_Training> Distributors_Training { get; set; }
        public virtual DbSet<Distributors_Training_Attendance_History> Distributors_Training_Attendance_History { get; set; }
        public virtual DbSet<Dopay> Dopays { get; set; }
        public virtual DbSet<Dopay_Activation> Dopay_Activation { get; set; }
        public virtual DbSet<dopay_close> dopay_close { get; set; }
        public virtual DbSet<DynamicPage> DynamicPages { get; set; }
        public virtual DbSet<Easy_pay_Acc> Easy_pay_Acc { get; set; }
        public virtual DbSet<Easy_pay_cards> Easy_pay_cards { get; set; }
        public virtual DbSet<Elite_Category> Elite_Category { get; set; }
        public virtual DbSet<Elite_Comments> Elite_Comments { get; set; }
        public virtual DbSet<Elite_Place_Branchs> Elite_Place_Branchs { get; set; }
        public virtual DbSet<Elite_Place_Images> Elite_Place_Images { get; set; }
        public virtual DbSet<Elite_Places> Elite_Places { get; set; }
        public virtual DbSet<Event_Distributor_Relatives> Event_Distributor_Relatives { get; set; }
        public virtual DbSet<Event_Valid_Distributors> Event_Valid_Distributors { get; set; }
        public virtual DbSet<EventCalendar> EventCalendars { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Events_Ticket_Holders> Events_Ticket_Holders { get; set; }
        public virtual DbSet<Fawry_Payment> Fawry_Payment { get; set; }
        public virtual DbSet<GalleryList> GalleryLists { get; set; }
        public virtual DbSet<GalleryPhoto> GalleryPhotos { get; set; }
        public virtual DbSet<Governorate> Governorates { get; set; }
        public virtual DbSet<HealthCare_News> HealthCare_News { get; set; }
        public virtual DbSet<Image_Slider> Image_Slider { get; set; }
        public virtual DbSet<Invitation> Invitations { get; set; }
        public virtual DbSet<Kinship_Degree> Kinship_Degree { get; set; }
        public virtual DbSet<Label> Labels { get; set; }
        public virtual DbSet<Layout> Layouts { get; set; }
        public virtual DbSet<Level_History> Level_History { get; set; }
        public virtual DbSet<Level_Status_Ranks> Level_Status_Ranks { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Means_Of_Communication> Means_Of_Communication { get; set; }
        public virtual DbSet<Membership_Status> Membership_Status { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Network_Distributor_History> Network_Distributor_History { get; set; }
        public virtual DbSet<Network_Video> Network_Video { get; set; }
        public virtual DbSet<News_Slider> News_Slider { get; set; }
        public virtual DbSet<NS_Activation> NS_Activation { get; set; }
        public virtual DbSet<NS_Payments> NS_Payments { get; set; }
        public virtual DbSet<NS_Starting_Balance> NS_Starting_Balance { get; set; }
        public virtual DbSet<NS_Transactions> NS_Transactions { get; set; }
        public virtual DbSet<NS_Upgrade> NS_Upgrade { get; set; }
        public virtual DbSet<Online_Category> Online_Category { get; set; }
        public virtual DbSet<Online_Courses> Online_Courses { get; set; }
        public virtual DbSet<Online_Courses_Details> Online_Courses_Details { get; set; }
        public virtual DbSet<Online_Courses_Level> Online_Courses_Level { get; set; }
        public virtual DbSet<Online_Courses_Packages> Online_Courses_Packages { get; set; }
        public virtual DbSet<Online_Courses_URL> Online_Courses_URL { get; set; }
        public virtual DbSet<Online_Distributor_Courses> Online_Distributor_Courses { get; set; }
        public virtual DbSet<Online_Distributor_History> Online_Distributor_History { get; set; }
        public virtual DbSet<Online_Distributor_Packages> Online_Distributor_Packages { get; set; }
        public virtual DbSet<Online_Distributor_Status> Online_Distributor_Status { get; set; }
        public virtual DbSet<Online_Instructor> Online_Instructor { get; set; }
        public virtual DbSet<Online_Packages> Online_Packages { get; set; }
        public virtual DbSet<Online_Payment_Parameters> Online_Payment_Parameters { get; set; }
        public virtual DbSet<Online_Upgrade_Packages> Online_Upgrade_Packages { get; set; }
        public virtual DbSet<Package> Packages { get; set; }
        public virtual DbSet<Packages_Products> Packages_Products { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Payment_Transactions_NS> Payment_Transactions_NS { get; set; }
        public virtual DbSet<Place_Branches> Place_Branches { get; set; }
        public virtual DbSet<Place_Specialization> Place_Specialization { get; set; }
        public virtual DbSet<Place_Suggestions> Place_Suggestions { get; set; }
        public virtual DbSet<Place_Suggestions_Admin_Reply> Place_Suggestions_Admin_Reply { get; set; }
        public virtual DbSet<Place_Ticket> Place_Ticket { get; set; }
        public virtual DbSet<Place_Ticket_Branches> Place_Ticket_Branches { get; set; }
        public virtual DbSet<Place_Ticket_WorkFlow> Place_Ticket_WorkFlow { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Plan_B_Balance_Sheet> Plan_B_Balance_Sheet { get; set; }
        public virtual DbSet<POC_Distributor> POC_Distributor { get; set; }
        public virtual DbSet<POC_Temp> POC_Temp { get; set; }
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<Print_Certificate_History> Print_Certificate_History { get; set; }
        public virtual DbSet<Print_History> Print_History { get; set; }
        public virtual DbSet<Print_Types> Print_Types { get; set; }
        public virtual DbSet<Product_Equations> Product_Equations { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Profit> Profits { get; set; }
        public virtual DbSet<Profit_Distributing_History> Profit_Distributing_History { get; set; }
        public virtual DbSet<Profit_ISave_Membership> Profit_ISave_Membership { get; set; }
        public virtual DbSet<Profit_Payment_Type> Profit_Payment_Type { get; set; }
        public virtual DbSet<Request> Requests { get; set; }
        public virtual DbSet<Shipping_Details> Shipping_Details { get; set; }
        public virtual DbSet<Shipping_Distributor_Products> Shipping_Distributor_Products { get; set; }
        public virtual DbSet<Shipping_Products> Shipping_Products { get; set; }
        public virtual DbSet<Sponser_Offer> Sponser_Offer { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Training_Details> Training_Details { get; set; }
        public virtual DbSet<Travel_Cities> Travel_Cities { get; set; }
        public virtual DbSet<Travel_Offer> Travel_Offer { get; set; }
        public virtual DbSet<Travel_Offer_Images> Travel_Offer_Images { get; set; }
        public virtual DbSet<Upgrade_Temp> Upgrade_Temp { get; set; }
        public virtual DbSet<Upgrade> Upgrades { get; set; }
        public virtual DbSet<work_zone_area> work_zone_area { get; set; }
        public virtual DbSet<Distributors_Addon_Coins_12_06_2020> Distributors_Addon_Coins_12_06_2020 { get; set; }
        public virtual DbSet<Distributors_Summit_Coins_12_06_2020> Distributors_Summit_Coins_12_06_2020 { get; set; }
        public virtual DbSet<Distributors_Summit_Coins_old> Distributors_Summit_Coins_old { get; set; }
        public virtual DbSet<Free_Courses> Free_Courses { get; set; }
        public virtual DbSet<MenuLocation> MenuLocations { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<NewsLetter> NewsLetters { get; set; }
        public virtual DbSet<N> NS { get; set; }
        public virtual DbSet<Online_Distributors_Point> Online_Distributors_Point { get; set; }
        public virtual DbSet<PagePrgrph> PagePrgrphs { get; set; }
        public virtual DbSet<Payment_Method> Payment_Method { get; set; }
        public virtual DbSet<POC> POCs { get; set; }
        public virtual DbSet<Product_Brands> Product_Brands { get; set; }
        public virtual DbSet<Product_Category> Product_Category { get; set; }
        public virtual DbSet<Products_Scratch_Cards> Products_Scratch_Cards { get; set; }
        public virtual DbSet<Profit_Advanced_Network> Profit_Advanced_Network { get; set; }
        public virtual DbSet<Profit_Profit_Diff> Profit_Profit_Diff { get; set; }
        public virtual DbSet<Sales_Receipt> Sales_Receipt { get; set; }
        public virtual DbSet<Testimonial> Testimonials { get; set; }
        public virtual DbSet<Travel_Reservation> Travel_Reservation { get; set; }
        public virtual DbSet<Upgrade_Membership_History> Upgrade_Membership_History { get; set; }
        public virtual DbSet<Upgrade_Program_History> Upgrade_Program_History { get; set; }
        public virtual DbSet<Video_Category> Video_Category { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<Visitors_Counter> Visitors_Counter { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<VotesAnswer> VotesAnswers { get; set; }
    }
}
