//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_Courses_Details
    {
        public int ID { get; set; }
        public string Lesson_Ar { get; set; }
        public string Lesson_En { get; set; }
        public Nullable<int> Online_Courses_ID { get; set; }
        public Nullable<bool> Is_free { get; set; }
        public Nullable<bool> Is_intro { get; set; }
        public string Url { get; set; }
    }
}
