//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_Upgrade_Packages
    {
        public int ID { get; set; }
        public string Upgrade_Name { get; set; }
        public string Image_URL { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Old_Package { get; set; }
        public Nullable<int> New_Package { get; set; }
    }
}
