//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_Packages
    {
        public int ID { get; set; }
        public string Packages_Name { get; set; }
        public string Imge { get; set; }
        public Nullable<decimal> Original_Price { get; set; }
        public Nullable<decimal> Price_After_Discount { get; set; }
        public Nullable<decimal> Distributor_Price { get; set; }
        public Nullable<int> No_of_Courses { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
