//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Online_Courses
    {
        public int ID { get; set; }
        public string Name_Ar { get; set; }
        public string Name_En { get; set; }
        public string Imge { get; set; }
        public Nullable<int> Number_Of_Videos { get; set; }
        public Nullable<int> Online_Category_ID { get; set; }
        public Nullable<int> Online_course_Level_ID { get; set; }
        public Nullable<int> Online_Instructor_ID { get; set; }
        public Nullable<System.TimeSpan> Total_hourse { get; set; }
        public Nullable<decimal> Original_Price { get; set; }
        public Nullable<decimal> Price_After_Discount { get; set; }
        public Nullable<decimal> Distributor_Price { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string URL { get; set; }
    }
}
