//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment_Transactions_NS
    {
        public int ID { get; set; }
        public Nullable<int> NS_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Total_Today_Amount { get; set; }
        public Nullable<int> Transfered_To_ID { get; set; }
        public string Transaction_ID { get; set; }
        public Nullable<System.DateTime> Transaction_Date { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Description { get; set; }
        public Nullable<bool> NS_Is_Paid { get; set; }
        public Nullable<System.DateTime> NS_Paid_Date { get; set; }
        public Nullable<bool> Accountant_Is_Paid { get; set; }
        public Nullable<System.DateTime> Accountant_Payment_Date { get; set; }
    }
}
