//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_Suggestions
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public string Place_Name { get; set; }
        public Nullable<int> Gov_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> Suggestion_Date { get; set; }
    }
}
