//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type_ID { get; set; }
        public Nullable<int> Specialize_ID { get; set; }
        public string CP_Name { get; set; }
        public string Phone_1 { get; set; }
        public string Phone_2 { get; set; }
        public string Discount_Percentage { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Account_Manager_Name { get; set; }
        public string Account_Manager_Phone { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public string Code { get; set; }
    }
}
