//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POC_Distributor
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public Nullable<int> POC_ID { get; set; }
        public Nullable<System.DateTime> Subscription_Date { get; set; }
        public Nullable<decimal> Subscription_Cost { get; set; }
        public Nullable<bool> Is_Confirmed { get; set; }
        public Nullable<System.DateTime> Conformation_Date { get; set; }
    }
}
