//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Scratch_Cards
    {
        public int ID { get; set; }
        public string Serial { get; set; }
        public string Scratch_Serial { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public Nullable<int> Product_Cost_Type_ID { get; set; }
        public Nullable<bool> Is_Used { get; set; }
        public Nullable<int> User_For_Distributor_ID { get; set; }
        public Nullable<System.DateTime> Activation_Date { get; set; }
        public Nullable<System.DateTime> Sell_Date { get; set; }
        public Nullable<int> Sell_By { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<bool> Used_From_WebSite { get; set; }
    }
}
