//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Equations
    {
        public int ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<int> Cost_of_the_company { get; set; }
        public Nullable<int> Diploma { get; set; }
        public Nullable<int> B_V { get; set; }
        public Nullable<int> D_C { get; set; }
        public Nullable<int> A_L_A { get; set; }
        public Nullable<int> SMART_APP { get; set; }
        public Nullable<int> Shipping { get; set; }
    }
}
