//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Product_Type_ID { get; set; }
        public Nullable<int> Product_Brand_ID { get; set; }
        public Nullable<int> Cost_Points { get; set; }
        public Nullable<int> Profit_Points { get; set; }
        public Nullable<int> Management_Points { get; set; }
        public Nullable<int> Shipping_Points { get; set; }
        public Nullable<int> Redeem_Points { get; set; }
        public string Image { get; set; }
        public string Details { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Travel_Discount { get; set; }
        public Nullable<int> Total_Cost { get; set; }
        public Nullable<int> Contract_Cost { get; set; }
        public Nullable<bool> Is_Upgrade { get; set; }
        public string Package_Type { get; set; }
        public Nullable<bool> Is_Package { get; set; }
        public Nullable<int> Package_ID { get; set; }
        public string Product_Hint { get; set; }
        public Nullable<decimal> Sponsor_Points { get; set; }
        public Nullable<decimal> Summit_Coins { get; set; }
        public Nullable<decimal> Summit_Cost { get; set; }
    }
}
