//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Receipt
    {
        public long Receipt_Serial { get; set; }
        public Nullable<int> Distributors_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Receipt_Date { get; set; }
        public string Payment_Type { get; set; }
    }
}
