//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping_Distributor_Products
    {
        public int ID { get; set; }
        public int Distributor_ID { get; set; }
        public Nullable<int> Shipping_Product_ID { get; set; }
        public Nullable<int> Shipping_Details_ID { get; set; }
    }
}
