//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training_Details
    {
        public int ID { get; set; }
        public Nullable<int> Diploma_ID { get; set; }
        public Nullable<int> Course_Location_ID { get; set; }
        public string Attendance_Date { get; set; }
        public Nullable<int> Number_Of_Dates { get; set; }
        public Nullable<int> Instructor_ID { get; set; }
        public Nullable<bool> Is_Active { get; set; }
        public Nullable<int> Available_Seats { get; set; }
        public string Note { get; set; }
    }
}
