//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Offer
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Details { get; set; }
        public Nullable<int> Cost_Points { get; set; }
        public Nullable<decimal> AddValuePerson { get; set; }
        public Nullable<bool> Is_Active { get; set; }
    }
}
