//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel_Reservation
    {
        public int ID { get; set; }
        public Nullable<int> Hotel_ID { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Child_Count { get; set; }
        public Nullable<int> Adult_Count { get; set; }
        public Nullable<int> addition_Adult_Cont { get; set; }
        public Nullable<decimal> Reservation_Cost_Before { get; set; }
        public Nullable<decimal> Reservation_Cost_After { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public Nullable<bool> Is_Confirmed { get; set; }
        public Nullable<int> Confirmed_By { get; set; }
        public Nullable<System.DateTime> Confirmation_Date { get; set; }
        public Nullable<int> Travel_Offer_ID { get; set; }
        public string Travel_Discount { get; set; }
    }
}
