//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upgrade_Membership_History
    {
        public int ID { get; set; }
        public Nullable<int> Distributor_ID { get; set; }
        public Nullable<int> Old_Membership { get; set; }
        public Nullable<int> New_Membership { get; set; }
        public Nullable<decimal> Paid_Amount { get; set; }
        public Nullable<System.DateTime> Upgrade_Date { get; set; }
    }
}
