//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotesAnswer
    {
        public int VoteAnswer_ID { get; set; }
        public string VoteAnswer_BodyAR { get; set; }
        public string VoteAnswer_Body { get; set; }
        public Nullable<int> VoteAnswer_Hits { get; set; }
        public Nullable<int> VoteAnswer_Vote_ID { get; set; }
    }
}
