//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OldDatabaseModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int Vote_ID { get; set; }
        public string Vote_TitleAR { get; set; }
        public string Vote_Title { get; set; }
        public string Vote_BodyAR { get; set; }
        public string Vote_Body { get; set; }
        public Nullable<bool> Vote_Active { get; set; }
    }
}
